[FIX] attachment_unindex_content: unsupported param on _index method
Odoo introduced a new param `checksum` to the method `_index` on the
attachment model [1]. Since that param is not supported on this model,
the following error is now being raised:

    TypeError: _index() got an unexpected keyword argument 'checksum'

[1] https://github.com/odoo/odoo/commit/3d59cc84