[FIX] Add missing depend
Without explicit web dependency all tests fail like this:

File "/home/odoo/src/odoo/odoo/models.py", line 6905, in onchange
    raise NotImplementedError("onchange() is implemented in module 'web'")
NotImplementedError: onchange() is implemented in module 'web'