Remove encoding declaration from XML view
It's no longer supported in lxml:

      File "/opt/odoo/external-src/server-tools/server_environment/serv_config.py", line 228, in _build_osv
        cls._arch = etree.fromstring(arch)
      File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:82934)
      File "src/lxml/parser.pxi", line 1814, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:124471)
    ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.