[FIX] upgrade_analysis: prevent dependency on MarkupSafe >= 2.0.0
This halts test jobs on `could not obtain odoo.addons.__path__ using python` due
to the incompatibility of Odoo 16's required version of Jinja2 on Python 3.10

```
+ unbuffer /opt/odoo-venv/bin/odoo -d odoo -i account,base,base_import,base_setup,base_sparse_field,bus,crm,fs_storage,iap,mail,mail_environment,purchase,queue_job,sale_management,test_mail,web --http-interface=127.0.0.1 --stop-after-init
Traceback (most recent call last):
  File "/opt/odoo-venv/bin/odoo", line 5, in <module>
    import odoo
  File "/opt/odoo/odoo/__init__.py", line 155, in <module>
    from . import cli
  File "/opt/odoo/odoo/cli/__init__.py", line 11, in <module>
    from . import scaffold
  File "/opt/odoo/odoo/cli/scaffold.py", line 8, in <module>
    import jinja2
  File "/opt/odoo-venv/lib/python3.10/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/opt/odoo-venv/lib/python3.10/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/opt/odoo-venv/lib/python3.10/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/opt/odoo-venv/lib/python3.10/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/opt/odoo-venv/lib/python3.10/site-packages/markupsafe/__init__.py)
```